title: "Rosie"

socials:
  - name: "YouTube"
    url:  "https://youtube.com/channel/UCROkaAoBA2huDt76FytJFFg"
    icon: "youtube.svg"
  - name: "Bluesky"
    url:  "https://bsky.app/profile/did:plc:pq2ioq3xcf7fxaxrrc4bgjwp"
    icon: "bluesky.svg"
  - name: "Instagram"
    url:  "https://instagram.com/cosmic.auroracle"
    icon: "instagram.svg"
  - name: "Twitch"
    url:  "https://twitch.tv/CosmicAuroracle"
    icon: "twitch.svg"