title: "Rosie&#10024;"
name: "<b style=\"color: var(--color-primary)\">Rosie</b>"

socials:
  - name: "Bluesky"
    url:  "https://bsky.app/profile/did:plc:pq2ioq3xcf7fxaxrrc4bgjwp"
    icon: "bluesky.svg"
  - name: "Discord"
    url:  "https://discord.com/users/350041932057149441"
    icon: "discord.svg"
  - name: "Instagram"
    url:  "https://instagram.com/cosmic.auroracle"
    icon: "instagram.svg"
  - name: "Steam"
    url:  "https://steamcommunity.com/profiles/76561198027615249"
    icon: "steam.svg"
  - name: "Twitch"
    url:  "https://twitch.tv/CosmicAuroracle"
    icon: "twitch.svg"
  - name: "YouTube"
    url:  "https://youtube.com/channel/UCROkaAoBA2huDt76FytJFFg"
    icon: "youtube.svg"